refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{h([{l:0.1}|{d(%y%m%d %H:%M:%S)}|{P}|{t}|{T}:{M}:{f}:{L}])} {m}{n}"
  {{cookiecutter.package_name}}:
    kind: file
    path: "log/{{cookiecutter.package_name}}.log"
    encoder:
      pattern: "[{l:0.1}|{d(%y%m%d %H:%M:%S)}|{P}|{t}|{T}:{M}:{f}:{L}] {m}{n}"
root:
  level: debug
  appenders:
    - stdout
loggers:
  {{cookiecutter.package_name}}:
    level: info
    appenders:
      - stdout
      - {{cookiecutter.package_name}}
    additive: false
